// Generated by gencpp from file ros_openpose/Pixel.msg
// DO NOT EDIT!


#ifndef ROS_OPENPOSE_MESSAGE_PIXEL_H
#define ROS_OPENPOSE_MESSAGE_PIXEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_openpose
{
template <class ContainerAllocator>
struct Pixel_
{
  typedef Pixel_<ContainerAllocator> Type;

  Pixel_()
    : x(0.0)
    , y(0.0)  {
    }
  Pixel_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::ros_openpose::Pixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_openpose::Pixel_<ContainerAllocator> const> ConstPtr;

}; // struct Pixel_

typedef ::ros_openpose::Pixel_<std::allocator<void> > Pixel;

typedef boost::shared_ptr< ::ros_openpose::Pixel > PixelPtr;
typedef boost::shared_ptr< ::ros_openpose::Pixel const> PixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_openpose::Pixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_openpose::Pixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_openpose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_openpose': ['/home/sj/Desktop/ARAICodes/catkin_ws/src/ros_openpose/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Pixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_openpose::Pixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Pixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_openpose::Pixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Pixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_openpose::Pixel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_openpose::Pixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::ros_openpose::Pixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_openpose::Pixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_openpose/Pixel";
  }

  static const char* value(const ::ros_openpose::Pixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_openpose::Pixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The location and score of body parts are stored in a float array.\n\
# Therefore we are using 32 bits instead of 64 bits.\n\
# src: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/core/datum.hpp\n\
# The location has been resized to the desired output\n\
# resolution (e.g., `resolution` flag in the demo).\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::ros_openpose::Pixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_openpose::Pixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_openpose::Pixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_openpose::Pixel_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_OPENPOSE_MESSAGE_PIXEL_H
