LIBNAME = navigation
EXTRA_OBJ = navigation.o
EXTRA_CFLAGS += -DNDEBUG
#EXTRA_LINK = ../../Robots/Transform/Transform.o
include ../../Makefile.inc
CXXFLAGS += -std=c++11
#INCLUDES += -Iinclude -I../../Robots/Transform
