#!/bin/bash
### BEGIN INIT INFO
# Provides: naver robotics
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: naver
# Description: naver robot startup
### END INIT INFO

KERNEL=`uname -r`


cd ~/Desktop/SUSANGBOT/
/usr/local/bin/luajit start_robot.lua
